# Generated by Django 3.1 on 2020-08-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_date', models.DateField(verbose_name='date joined')),
                ('project_type', models.CharField(choices=[('F', 'Fully Sponsored'), ('G', 'Grantor Grantee'), ('A', 'Affiliated'), ('U', 'Unspecified')], default='U', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1024)),
                ('expense_description', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('receipts_url', models.URLField()),
                ('payee_name', models.CharField(max_length=200)),
                ('additional_comments', models.TextField()),
                ('street_address_1', models.CharField(max_length=200)),
                ('street_address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('N', 'Not Provided'), ('A', 'Ach'), ('W', 'Wire'), ('P', 'Paypal')], default='N', max_length=2)),
                ('ach_account_holder', models.CharField(max_length=200)),
                ('ach_routing_number', models.CharField(max_length=200)),
                ('ach_account_number', models.CharField(max_length=200)),
                ('ach_account_type', models.CharField(max_length=200)),
                ('wire_bank_id', models.CharField(max_length=200)),
                ('wire_bank_name', models.CharField(max_length=200)),
                ('wire_bank_address', models.CharField(max_length=200)),
                ('wire_account_holder', models.CharField(max_length=200)),
                ('wire_iban', models.CharField(max_length=200)),
                ('paypal_email', models.EmailField(max_length=254)),
                ('submit_date', models.DateField(verbose_name='date submitted')),
                ('approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField()),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='core.projectmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitter', to='core.projectmember')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinancialTeam',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.project')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('members', models.ManyToManyField(to='core.ProjectMember')),
            ],
        ),
    ]
